# Warps
Warps:
  DefaultLimit: 3 # Default limit for warp setting
  LimitNodes: [5, 10] # Permissions nodes to generate for warp limits (warptastix.limit.#)

# Homes
Homes:
  HomeOnDeath: false # Whether to teleport players home on death instead of to their bed

# Spawn management
Spawn:
  SpawnAtSpawn: true # Whether to spawn players at the world spawn or not
  ServerSpawn: true # Whether to use the server spawn or the world spawn

# Teleportation effect
TeleportEffect:
  Enable: true # Whether to play teleportation effects on warp or not
  Duration: 1.5 # The duration of the teleportation effects, in seconds

# Signs
Signs:
  Enable: true # Whether to enable warp signs or not
  WarpSignText: "[Warp]" # The text written to create warp signs
  WarpSignTitle: "&a[Warp]" # The title line for warp signs
  SpawnSignText: "[Spawn]" # The text written to create spawn teleport signs
  SpawnSignTitle: "&a[Spawn]" # The title line for spawn teleport signs
  ChargeOnSign: false # Whether to charge players for using signs or not

# Economy
Economy:
  Enable: true # Whether to enable economy integration or not - requires Vault!
  Warp:
    SetPrice: 100 # Price on setting warps
    WarpPrice: 0 # Price on warping to warps
  Home:
    SetPrice: 100 # Price on setting homes
    WarpPrice: 0 # Price on warping to homes
  Spawn:
    WarpPrice: 0 # Price on warping to spawn