name: Warptastix
version: ${project.version}
description: Continuation of Warptastic.
website: http://phanta.xyz
main: io.github.phantamanta44.warptastix.Warptastixix
softdepend: [Vault]
commands:
  warp:
    usage: "/warp <warp> [player]"
    description: Travels to a warp.
  warps:
    usage: "/warps [-pop] [-s|owner] [page#]"
    description: Lists warps.
  mywarps:
    usage: "/mywarps [page#]"
    description: Lists only your warps.
  warpinfo:
    usage: "/warpinfo <warp>"
    description: Displays details about a warp.
  setwarp:
    usage: "/setwarp [-p|-s] <warp> [owner]"
    description: Creates a new warp or toggles a flag on a warp.
  delwarp:
    usage: "/delwarp <warp>"
    description: Deletes a warp.
  clearwarps:
    usage: "/clearwarps <player>"
    description: Clears a player's warps.
  sethome:
    usage: "/sethome [owner]"
    description: Sets your home location.
  delhome:
    usage: "/delhome"
    description: Deletes your home location.
  home:
    usage: "/home [owner] [player]"
    description: Travels to your home location.
  spawn:
    usage: "/spawn [player]"
    description: Travels to the world spawn.
permissions:
  warptastix.warp:
    description: Allows you to use warps.
  warptastix.warp.other:
    description: Allows you to warp other players.
  warptastix.setwarp.public:
    description: Allows you to set public warps.
  warptastix.setwarp.private:
    description: Allows you to set private warps.
  warptastix.setwarp.other:
    description: Allows you to set warps for other players.
  warptastix.limit.unlimited:
    description: Allows you to ignore warp limits.
  warptastix.list:
    descritpion: Allows you to list warps.
  warptastix.list.other:
    descritpion: Allows you to list another player's warps.
  warptastix.makesign:
    description: Allows you to make warp signs.
  warptastix.info:
    description: Allows you to view warp info.
  warptastix.home:
    description: Allows you to set and use homes.
  warptastix.home.other:
    description: Allows you to set and use another player's home.
  warptastix.spawn:
    description: Allows you to teleport to spawn.
  warptastix.nocost:
    description: Allows you to bypass all prices.
  warptastix.nowarmup:
    description: Allows you to bypass all warmup times.
  warptastix.nocooldown:
    description: Allows you to bypass all cooldown times.